ForumApplication/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ForumApplication.Models
{
    public class User
    {
        [Key]
        public int UserID { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public byte[] Avatar { get; set; }
        public byte[] BackgroundImage { get; set; }

        public ICollection<Post> Posts { get; set; }
    }
}

ForumApplication/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ForumApplication.Models;
using ForumApplication.Helpers;

namespace ForumApplication.Controllers
{
    public class PostController : Controller
    {
        [HttpGet]
        public ActionResult PostNo(int ID)
        {
            using (ForumContext context = new ForumContext())
            {
                Post overPost = context.Posts.FirstOrDefault(x => x.PostID.Equals(ID));
                User user = context.Users.Find(overPost.UserId);

                PostCreateModel postModel = new PostCreateModel
                {
                    PostID = overPost.PostID,
                    Content = overPost.Content,
                    Date = overPost.PublicationDate.ToString(),
                    Username = user.Username
                };

                if (user.Avatar != null)
                {
                    string base64 = Convert.ToBase64String(user.Avatar);
                    string imgsrc = string.Format($"data:image/gif;base64,{base64}");
                    postModel.ProfileImage = imgsrc;
                }

                if (overPost.ImageFile != null)
                {
                    string base64 = Convert.ToBase64String(overPost.ImageFile);
                    string imgsrc = string.Format($"data:image/gif;base64,{base64}");
                    postModel.Image = imgsrc;
                }


                return View(postModel);
            }
        }

        [HttpGet]
        [Authorize]
        public PartialViewResult CreatePost(int PostID)
        {
            using (ForumContext context = new ForumContext())
            {
                Post overPost = context.Posts.FirstOrDefault(x => x.PostID.Equals(PostID));
                User user = context.Users.Find(overPost.UserId);

                PostCreateModel postModel = new PostCreateModel
                {
                    PostID = overPost.PostID,
                    Content = overPost.Content,
                    Date = overPost.PublicationDate.ToString(),
                    Username = user.Username
                };

                if (user.Avatar != null)
                {
                    string base64 = Convert.ToBase64String(user.Avatar);
                    string imgsrc = string.Format($"data:image/gif;base64,{base64}");
                    postModel.ProfileImage = imgsrc;
                }

                if (overPost.ImageFile != null)
                {
                    string base64 = Convert.ToBase64String(overPost.ImageFile);
                    string imgsrc = string.Format($"data:image/gif;base64,{base64}");
                    postModel.Image = imgsrc;
                }

                return PartialView("CreatePost", postModel);
            }
        }

        [HttpGet]
        public PartialViewResult CardPartial(int PostID)
        {
            using (ForumContext context = new ForumContext())
            {
                var overPost = context.Posts.FirstOrDefault(x => x.PostID.Equals(PostID));
                var postAuthor = context.Users.FirstOrDefault(x => x.UserID == overPost.UserId);

                Models.Helpers repository = new Models.Helpers();
                User loggedUser = repository.GetUser(User.Identity.Name);
                bool isLiked = false;

                if (loggedUser != null)
                    repository.IsLiked(overPost.PostID, loggedUser.UserID);

                PostCreateModel postModel = new PostCreateModel
                {
                    PostID = overPost.PostID,
                    Content = overPost.Content,
                    Date = ViewHelpers.DateCounter(overPost.PublicationDate),
                    CommentsNum = overPost.Posts.Count,
                    Username = postAuthor.Username,
                    IsLiked = isLiked,
                    Likes = overPost.Likes
                };

                if (postAuthor.Avatar != null)
                {
                    var base64 = Convert.ToBase64String(postAuthor.Avatar);
                    var imgsrc = string.Format($"data:image/gif;base64,{base64}");
                    postModel.ProfileImage = imgsrc;
                }
                else
                {
                    postModel.ProfileImage = null;
                }

                if (overPost.ImageFile != null)
                {
                    var base64 = Convert.ToBase64String(overPost.ImageFile);
                    var imgsrc = string.Format($"data:image/gif;base64,{base64}");
                    postModel.Image = imgsrc;
                }
                else
                {
                    postModel.Image = null;
                }

                return PartialView("CardPartial", postModel);
            }
        }

        [HttpPost]
        [Authorize]
        public ActionResult CreatePost(HttpPostedFileBase ImageFile = null, int PostID = -1)
        {
            byte[] data;
            Post overPost;
            string username = HttpContext.User.Identity.Name;

            if (ImageFile != null)
            {
                using (Stream inputStream = ImageFile.InputStream)
                {
                    MemoryStream memoryStream = inputStream as MemoryStream;
                    if (memoryStream == null)
                    {
                        memoryStream = new MemoryStream();
                        inputStream.CopyTo(memoryStream);
                    }
                    data = memoryStream.ToArray();
                }
            }
            else
            {
                data = null;
            }

            using (ForumContext context = new ForumContext())
            {
                User user = context.Users.FirstOrDefault(x => x.Username.Equals(username));

                Post newPost = new Post()
                {
                    Content = Request["Content"],
                    User = user,
                    PublicationDate = DateTime.Now,
                    ImageFile = data
                };

                if (PostID != -1)
                {
                    overPost = context.Posts.FirstOrDefault(x => x.PostID.Equals(PostID));
                    newPost.IsComment = true;
                    overPost.Posts.Add(newPost);
                }

                context.Posts.Add(newPost);
                context.SaveChanges();
            }

            return RedirectToAction("PostWall");
        }

        [HttpGet]
        public ActionResult PostWall() => View();

        [HttpPost]
        [Authorize]
        public JsonResult Like(int PostID)
        {
            Models.Helpers repository = new Models.Helpers();
            int userid = repository.GetUser(User.Identity.Name.ToString()).UserID;

            int result = repository.Like(PostID, userid);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetPosts(int pageNumber, int pageSize)
        {
            Models.Helpers repository = new Models.Helpers();
            List<PostCreateModel> postList = new List<PostCreateModel>();

            var items = repository.GetPosts(pageNumber, pageSize);

            foreach (var item in items)
            {
                PostCreateModel postModel = new PostCreateModel
                {
                    PostID = item.PostID
                };

                postList.Add(postModel);
            }
            return Json(postList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetComments(int OverPostID, int pageNumber, int pageSize)
        {
            Models.Helpers repository = new Models.Helpers();
            List<PostCreateModel> posts = new List<PostCreateModel>();

            foreach (var item in repository.GetPosts(OverPostID, pageNumber, pageSize))
            {
                PostCreateModel postModel = new PostCreateModel
                {
                    PostID = item.PostID,
                    Content = item.Content,
                    Date = item.PublicationDate.ToString()
                };

                if (item.ImageFile != null)
                {
                    var base64 = Convert.ToBase64String(item.ImageFile);
                    var imgsrc = string.Format($"data:image/gif;base64,{base64}");
                    postModel.Image = imgsrc;
                }
                else
                {
                    postModel.Image = null;
                }
                posts.Add(postModel);
            }

            return Json(posts, JsonRequestBehavior.AllowGet);
        }


    }
}

ForumApplication/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using ForumApplication.Models;

namespace ForumApplication.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public ActionResult Register() => View();

        [HttpPost]
        public ActionResult Register(User user)
        {
            Models.Helpers repository = new Models.Helpers();
            if (repository.RegisterUser(user))
            {
                return RedirectToAction("Login");
            }

            return View();
        }

        [HttpGet]
        public ActionResult Login() => View();

        [HttpPost]
        public ActionResult Login(User user)
        {
            Models.Helpers repository = new Models.Helpers();
            if (repository.SingInUser(user))
            {
                FormsAuthentication.RedirectFromLoginPage(user.Username, false);
            }

            return View();
        }

        [Authorize]
        public ActionResult Logout()
        {
            Session.Abandon();
            Request.Cookies.Clear();
            FormsAuthentication.SignOut();

            return RedirectToAction("Login");
        }

        [HttpGet]
        [Authorize]
        public ActionResult UserProfile(string Username)
        {
            if (Username == null) Username = User.Identity.Name;

            UserHelperModel userModel = new UserHelperModel();
            Models.Helpers repository = new Models.Helpers();

            string imgsrc;
            var user = repository.GetUser(Username);

            if (user.Avatar == null)
                imgsrc = "";
            else
            {
                var base64 = Convert.ToBase64String(user.Avatar);
                imgsrc = string.Format($"data:image/gif;base64,{base64}");
            }
            userModel.Avatar = imgsrc;

            if (user.BackgroundImage == null)
                imgsrc = "";
            else
            {
                var base64 = Convert.ToBase64String(user.BackgroundImage);
                imgsrc = string.Format($"data:image/gif;base64,{base64}");
            }
            userModel.BackgroundImage = imgsrc;
            userModel.Username = user.Username;


            return View(userModel);
        }

        [HttpPost]
        [Authorize]
        public ActionResult UserProfile(HttpPostedFileBase ProfileImageFile, HttpPostedFileBase BackgroundImageFile)
        {
            byte[] profile = null;
            byte[] background = null;

            if (ProfileImageFile != null)
            {
                using (Stream input = ProfileImageFile.InputStream)
                {
                    MemoryStream memory = input as MemoryStream;
                    if (memory == null)
                    {
                        memory = new MemoryStream();
                        input.CopyTo(memory);
                    }
                    profile = memory.ToArray();
                }
            }

            if (BackgroundImageFile != null)
            {
                using (Stream input = BackgroundImageFile.InputStream)
                {
                    MemoryStream memory = input as MemoryStream;
                    if (memory == null)
                    {
                        memory = new MemoryStream();
                        input.CopyTo(memory);
                    }
                    background = memory.ToArray();
                }
            }

            using (ForumContext context = new ForumContext())
            {
                User user = context.Users.SingleOrDefault(x => x.Username.Equals(User.Identity.Name));

                if (ProfileImageFile != null)
                    user.Avatar = profile;

                if (BackgroundImageFile != null)
                    user.BackgroundImage = background;

                context.SaveChanges();
            }

            return RedirectToAction("UserProfile");
        }

        public JsonResult GetUserPosts(string username, int pageNumber, int pageSize)
        {
            Models.Helpers repository = new Models.Helpers();
            List<PostCreateModel> postList = new List<PostCreateModel>();

            var items = repository.GetPosts(pageNumber, pageSize, username);
            string imgsrc;

            foreach (Post item in items)
            {
                if (item.ImageFile == null)
                    imgsrc = "";
                else
                {
                    var base64 = Convert.ToBase64String(item.ImageFile);
                    imgsrc = string.Format($"data:image/gif;base64,{base64}");
                }

                PostCreateModel postModel = new PostCreateModel
                {
                    PostID = item.PostID,
                    Content = item.Content,
                    Date = item.PublicationDate.ToString(),
                    Image = imgsrc
                };

                postList.Add(postModel);
            }

            return Json(postList, JsonRequestBehavior.AllowGet);
        }
    }
}

ForumApplication/Views/User/Login.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
<link href="~/Content/register.css" rel="stylesheet" />
@{
    ViewBag.Titile = "Login";
    Layout = "";
}

<div class="u-center border-section">
    @using (Html.BeginForm())
    {
        <form class="u-form">
            <div class="crd-title">
                <h1 class="bold">Login</h1>
                <p class="sm-text mb0">Fill fields below</p>
            </div>
            <div class="sec-single">
                <div class="crd">
                    <p class="sm-text">Username</p>
                    <input class="inpt" type="text" name="Username">
                    @*<i class="fas fa-check-circle field-ok"></i>*@
                    <i class="fas fa-times-circle field-nok"></i>
                </div>
            </div>
            <div class="sec-single">
                <div class="crd">
                    <p class="sm-text">Password</p>
                    <input class="inpt" type="password" name="Password">
                    <i class="fas fa-check-circle field-ok"></i>
                    @*<i class="fas fa-times-circle field-nok"></i>*@
                </div>
            </div>
            <div class="checkbox-div">
                <input type="checkbox" name="name" />
                <span> Remember me!</span>
            </div>
            <div class="u-form-footer">
                <input type="submit" class="u-button full" value="Submit" />
                <div class="sm-text txt-center">
                    <a href="/user/register">Or register here</a>
                </div>
            </div>
        </form>
    }
</div>

ForumApplication/Views/User/Register.cshtml
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
<link href="~/Content/register.css" rel="stylesheet" />
@{
    Layout = "";
}

<div class="u-center border-section">
    @using (Html.BeginForm())
    {
        <form class="u-form">
            <div class="crd-title">
                <h1 class="bold">Register</h1>
                <p class="sm-text">Fill fields below</p>
            </div>
            <div class="sec-single">
                <div class="crd">
                    <p class="sm-text">Username</p>
                    <input class="inpt" type="text" name="Username">
                    @*<i class="fas fa-check-circle field-ok"></i>*@
                    <i class="fas fa-times-circle field-nok"></i>
                </div>
            </div>
            <div class="sec-single">
                <div class="crd">
                    <p class="sm-text">Email</p>
                    <input class="inpt" type="email" name="Email">
                    @*<i class="fas fa-check-circle field-ok"></i>*@
                    <i class="fas fa-times-circle field-nok"></i>
                </div>
            </div>
            <div class="sec-single">
                <div class="crd">
                    <p class="sm-text">Password</p>
                    <input class="inpt" type="password" name="Password">
                    <i class="fas fa-check-circle field-ok"></i>
                    @*<i class="fas fa-times-circle field-nok"></i>*@
                </div>
            </div>
            <div class="sec-single">
                <div class="crd">
                    <p class="sm-text">Repeat password</p>
                    <input class="inpt" type="password">
                    <i class="fas fa-check-circle field-ok"></i>
                    @*<i class="fas fa-times-circle field-nok"></i>*@
                </div>
            </div>
            <div class="u-form-footer">
                <input class="u-button full" type="submit" value="Submit" />
                <div class="sm-text txt-center">
                    <a href="/user/login">Or login here</a>
                </div>
            </div>
        </form>
    }
</div>

ForumApplication/Views/User/UserProfile.cshtml
@model ForumApplication.Models.UserHelperModel


<div>
    <div class="background-profile">
        @using (Html.BeginForm("UserProfile", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div id="backgroundimage" style="z-index:2;">
                @if (Model.BackgroundImage != "")
                {
                    if (Model.Username == User.Identity.Name)
                    {
                        <div class="file">
                            <input style="visibility:hidden" type="file" name="BackgroundImageFile" id="BackgroundImageFile" class="inputfile" />
                            <label for="BackgroundImageFile">
                                <img src="@Model.BackgroundImage" />
                            </label>
                        </div>
                    }
                    else
                    {
                        <img src="@Model.BackgroundImage" />
                    }
                }
                else
                {
                    if (Model.Username == User.Identity.Name)
                    {
                        <div class="file">
                            <input style="visibility:hidden" type="file" name="BackgroundImageFile" id="BackgroundImageFile" class="inputfile" />
                            <label for="BackgroundImageFile">
                                <img src="~/Images/example.jpg" />
                            </label>
                        </div>
                    }
                    else
                    {
                        <img src="~/Images/example.jpg" />
                    }
                }
            </div>
            <div class="border-section foreground-profile">

                @if (Model.Avatar != "")
                {
                    if (Model.Username == User.Identity.Name)
                    {
                        <div class="file">
                            <input style="visibility:hidden" type="file" name="ProfileImageFile" id="ProfileImageFile" class="inputfile" />
                            <label for="ProfileImageFile">
                                <img src="@Model.Avatar" />
                            </label>
                        </div>
                    }
                    else
                    {
                        <img src="@Model.Avatar" />
                    }
                }
                else
                {
                    if (Model.Username == User.Identity.Name)
                    {
                        <div class="file">
                            <input style="visibility:hidden" type="file" name="ProfileImageFile" id="ProfileImageFile" class="inputfile" />
                            <label for="ProfileImageFile">
                                <img src="~/Icons/anon-avatar.jpg" />
                            </label>
                        </div>
                    }
                    else
                    {
                        <img src="~/Icons/anon-avatar.jpg" />
                    }
                }
                <h2>@Model.Username</h2>
                @if (Model.Username == User.Identity.Name)
                {
                    <input class="u-button" style="margin-top:-1em;" type="submit" value="Save" />
                }
            </div>
        }
    </div>

    <div class=" tabs-section">
        <a href="#" class="active-tab tabs-section-item">
            <div>
                All
            </div>
        </a>
        <a href="#" class="tabs-section-item">
            <div>
                Only posts
            </div>
        </a>
        <a href="#" class="tabs-section-item">
            <div>
                Only comments
            </div>
        </a>
    </div>
    <div id="postList" class="postlist">

    </div>
    <div id="footer">

    </div>
    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div id="content"></div>
        </div>
    </div>
</div>
<link href="~/Content/Modal.css" rel="stylesheet" />
<script>
    btn = $("#profile").addClass("btn-active");
</script>
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/modernizr-2.8.3.js"></script>
<script>
    $(document).ready(function () {

        var url = '@Url.Action("GetUserPosts", "User")';

        var currentPageNumber = 1;
        loadData(currentPageNumber, url);

        $(window).scroll(function () {
            var height = $(document).height() - $(window).height();

            if ($(window).scrollTop() - height > 100) {
                currentPageNumber += 1;
                loadData(currentPageNumber, url);
            }
        });

        function loadData(currentPage, url) {
            $.ajax({
                url: url,
                method: 'POST',
                data: {
                    username: '@Model.Username',
                    pageNumber: currentPage,
                    pageSize: 15
                },
                dataType: 'json',
                success: function (data) {
                    $.each(data, function (i, item) {

                        var postid = item.PostID;

                        $.ajax({
                            url: '@Url.Action("CardPartial", "Post")',
                            type: 'GET',
                            data: {
                                PostID: postid
                            },
                            success: function (result) {
                                $('#postList').append(result);
                            }
                        });
                    });
                }
            });
        }
    });
</script>
<script>
    var modal = document.getElementById("myModal");
    var btn = document.getElementById("myBtn");
    var span = document.getElementsByClassName("close")[0];

    function OpenModal() {

        var postid = $(event.target).closest("button").attr("value");

        $.ajax({
            url: '@Url.Action("CreatePost", "Post")',
            type: 'GET',
            data: {
                PostID: postid
            },
            error: function (xhr) {
                alert('Error: ' + xhr.statusText);
            },
            success: function (result) {
                $('#content').html(result);
            }
        });
        modal.style.display = "block";
    }

    span.onclick = function () {
        modal.style.display = "none";
    }

    window.onclick = function (event) {
        if (event.target == modal) {
            modal.style.display = "none";
        }
    }
</script>